services:
  nginx:
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:-app.seudominio.com}
    ports:
      - "80:80"
    volumes:
      - ./nginx/default-letsencrypt-acme.conf.template:/etc/nginx/templates/default.conf.template:ro
      - certbot-webroot:/var/www/certbot
