services:
  nginx:
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:-localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default-https.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/certs:/etc/nginx/certs:ro
